% Exercise - Understanding hypothesis tesing using simulation

%% 1. Clear workspace

% Clear
clear;

%% 2. Define t-value and degrees of freedom

% 2.1. Define t-value
tValue = 2;

% 2.2. Define degrees of freedom
nu = 20;

%% 3. Generate Student's t distributed values

% 3.1. Number of random draws
N = 20000;

% 3.2. Define histogram bin edges
binEdges = -6:0.01:6;

% 3.3. Construct t-distributed random variables
draws = StochasticRepresentation(N,nu);

% 3.4. Create histogram
figure;
set(gcf,'Position',[100 100 1000 1000]);
histogram(draws,...
    'BinEdges',binEdges,...
    'FaceColor',[0.700 0.700 0.700],...
    'EdgeAlpha',0,...
    'DisplayName','All simulated values');
xmin = icdf('T',0.0001,nu);
xmax = icdf('T',0.9999,nu);
xlim([xmin xmax]);
title(['Fig. 1. Histogram of simulated t-distributed draws', ...
       ', N = ',num2str(N), ...
       ', \nu = ', num2str(nu)]);
xlabel('t');
ylabel('Frequency');
legend('show');

%% 4. Add the t-statistic to the plot

% Plot histogram and t-statistic
figure;
set(gcf,'Position',[100 100 1000 1000]);
histogram(draws,...
    'BinEdges',binEdges,...
    'FaceColor',[0.700 0.700 0.700],...
    'EdgeAlpha',0,...
    'DisplayName','All simulated values');
hold on
xline(tValue,...
    'LineStyle',':',...
    'Color',[0.541 0.133 0.702],...
    'LineWidth',1.4,...
    'DisplayName','t-statistic');
xmin = icdf('T',0.0001,nu);
xmax = icdf('T',0.9999,nu);
xlim([xmin xmax]);
hold off
title(['Fig. 2. Histogram of simulated t-distributed draws', ...
       ', N = ',num2str(N), ...
       ', \nu = ',num2str(nu)]);
xlabel('t');
ylabel('Frequency');
legend('show');

%% 5. Highlight the extreme values and estimate the p-value by simulation

% 5.1. Select values exceeding the t-statistic
extremeValues = draws(draws > tValue);

% 5.2. Plot histogram and highlight values exceeding the t-statistic
figure;
set(gcf,'Position',[100 100 1000 1000]);
histogram(draws,...
    'BinEdges',binEdges,...
    'FaceColor',[0.700 0.700 0.700],...
    'EdgeAlpha',0,...
    'DisplayName','All simulated values');
hold on
histogram(extremeValues,...
    'BinEdges',binEdges,...
    'FaceColor',[0.541 0.133 0.702],...
    'EdgeAlpha',0,...
    'DisplayName','Values exceeding the t-statistic');
xline(tValue,...
    'LineStyle',':',...
    'Color',[0.541 0.133 0.702],...
    'LineWidth',1.4,...
    'DisplayName','t-statistic');
xmin = icdf('T',0.0001,nu);
xmax = icdf('T',0.9999,nu);
xlim([xmin xmax]);
hold off
title(['Fig. 3. Simulated values exceeding the t-statistic', ...
       ', N = ',num2str(N), ...
       ', \nu = ',num2str(nu)]);
xlabel('t');
ylabel('Frequency');
legend('show');

% 5.3. Estimate the right-tail probability (simulated p-value)
simulatedPValue = numel(extremeValues)/numel(draws);

%% 6. The critical-value and p-value approaches to hypothesis testing

% 6.1. Define the critical value and rejection region
criticalValue = 1.725;
criticalValueRegion = draws(draws > 1.725);
pValue = mean(draws > tValue);
pValueRegion = draws(draws > tValue);

% 6.2. Add the decision rule to the histogram
figure;
set(gcf,'Position',[100 100 1000 1000]);
% Full distribution
histogram(draws,...
    'BinEdges',binEdges,...
    'FaceColor',[0.700 0.700 0.700],...
    'EdgeAlpha',0,...
    'DisplayName','All simulated values');
hold on
% Rejection region
histogram(criticalValueRegion,...
    'BinEdges',binEdges,...
    'FaceColor',[0.604 0.604 0.988],...
    'FaceAlpha',0.15,...
    'EdgeAlpha',0,...
    'DisplayName','Critical value region');
% P-value region
histogram(pValueRegion,...
    'BinEdges',binEdges,...
    'FaceColor',[0.541 0.133 0.702],...
    'FaceAlpha',1,...
    'EdgeAlpha',0,...
    'DisplayName','p-value region');
% Critical value
xline(1.725,...
    'LineStyle',':',...
    'Color',[0.604 0.604 0.988],...
    'LineWidth',1.4,...
    'DisplayName','Critical value');
% Test statistic
xline(tValue,...
    'LineStyle',':',...
    'Color',[0.541 0.133 0.702],...
    'LineWidth',1.4,...
    'DisplayName','t-statistic');
xmin = icdf('T',0.0001,nu);
xmax = icdf('T',0.9999,nu);
xlim([xmin xmax]);
hold off
title(['Fig. 4. Simulated values exceeding the t-statistic',...
       ', N = ',num2str(N), ...
       ', \nu = ',num2str(nu)...
       ', t = ',num2str(tValue,'%.4f'), ...
       ', p-value = ',num2str(pValue,'%.4f')]);
xlabel('t');
ylabel('Frequency');
legend('show');

%% 7. Theoretical p-value calculation

% 7.1. Define evaluation points
xValues = -6:0.1:6;

% 7.2. Evaluate the PDF of the t-distribution
pdfValues = PDF(xValues,nu);

% 7.3. Plot the PDF and shade the p-value area
figure;
set(gcf,'Position',[100 100 1000 1000]);
plot(xValues,pdfValues,...
    'Color',[0.000 0.000 0.000],...
    'DisplayName','PDF');
hold on
% Critical value
xline(criticalValue,...
    'LineStyle',':',...
    'Color',[0.604 0.604 0.988],...
    'LineWidth',1.4,...
    'DisplayName','Critical value');
% Alpha = 0.05 rejection region
alphaRange = criticalValue:0.001:6;
alphaDensity = pdf('T',alphaRange,nu);
alphaArea = area(alphaRange,alphaDensity,...
    'DisplayName','Critical value region');
alphaArea.FaceColor = [0.604 0.604 0.988];
alphaArea.FaceAlpha = 0.15;
alphaArea.EdgeColor = 'none';
% Test statistic
xline(tValue,...
    'LineStyle',':',...
    'Color',[0.541 0.133 0.702],...
    'LineWidth',1.4,...
    'DisplayName','t-statistic');
% p-value region
tailRange = tValue:0.001:6;
tailDensity = pdf('T',tailRange,nu);
tailArea = area(tailRange,tailDensity,...
    'DisplayName','p-value region');
tailArea.FaceColor = [0.541 0.133 0.702];
tailArea.FaceAlpha = 1.00;
tailArea.EdgeColor = 'none';
xmin = min(-criticalValue,max(-10,icdf('T',0.0001,nu)));
xmax = max(criticalValue,min(10,icdf('T',0.9999,nu)));
xlim([xmin xmax]);
hold off
title(['Fig. 5. Theoretical PDF of the t-distribution with shaded',...
       ' p-value area', ...
       ', \nu = ',num2str(nu)]);
xlabel('t');
ylabel('Density');
legend('show');

% 7.4. Compare the theoretical and simulated p-values
theoreticalPValue = 1 - cdf('T',tValue,nu);
